name: First workflow

on: workflow_dispatch

jobs :
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Print Hello 
        run: echo "Hi, I am shivam"
      - name: Print Goodbye
        run : echo "bye"
      
      
