name: Build and Run 2-action

on:
  push:
    paths:
      - '2-action/**'
    branches: [ "main" ]
  pull_request:
    paths:
      - '2-action/**'
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

